### ISSUE TITLE
The `set-env` command is disabled

### ISSUE THREAD

**Issue by igor-makarov** [maxim-lobanov/setup-xcode#12]
I've begun getting this error on my repo:

```
Switching Xcode to version '11.5'...
Error: Unable to process command '::set-env name=MD_APPLE_SDK_ROOT::/Applications/Xcode_11.5.app' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Link - https://github.com/igor-makarov/RxReactiveObjC/runs/1411206039

I understand that I can opt into the old behavior, but I'd rather not, as there are known vulnerabilities in that approach.

Thanks for your help!

**Comment by maxim-lobanov** [comment]
Hello @igor-makarov !
This issue is already fixed in latest version of setup-xcode action.
Could you please update your YAML to use `maxim-lobanov/setup-xcode@v1` instead of `maxim-lobanov/setup-xcode@1.0`

**Comment by igor-makarov** [comment]
Thank you!
