### ISSUE TITLE
Why use this action instead of simply setting `DEVELOPER_DIR`?

### ISSUE THREAD

**Issue by ErikBjare** [maxim-lobanov/setup-xcode#16]
Apparently you can just set `DEVELOPER_DIR` to achieve the same result: https://github.community/t/selecting-an-xcode-version/16204

Any reasons why one would want to use this action instead?

**Comment by maxim-lobanov** [comment]
When you specify `DEVELOPER_DIR`, you have to specify exact path to Xcode.
Action allows to specify Xcode versions via
1) SemVer notation, something like `12.x` or `12.1.x`
2) `latest` and `latest-stable` keywords

**Comment by ErikBjare** [comment]
Ah, that makes sense.

I was fighting with Xcode today and mistakenly thought that setting `DEVELOPER_DIR` would solve my problems. But in the end, I found that all I really needed was to set `MACOSX_DEPLOYMENT_TARGET`: https://github.com/ActivityWatch/activitywatch/pull/544#issuecomment-751749253

Thanks for the reply, closing.
