### ISSUE TITLE
Provide output with resolved Xcode version

### ISSUE THREAD

**Issue by ffried** [maxim-lobanov/setup-xcode#26]
First of all: nice action! Thank you!

It would be nice, though, if there were an output which contains the Xcode version that was selected in the end. E.g. if the pattern specifies `^12.4` and the action resolves it to `12.5.1`, it's currently a bit of a hassle to get to the version string `12.5.1`. I'd like to use it in a cache key to limit cache issues across Xcode (or rather Swift) versions.

**Comment by maxim-lobanov** [comment]
Hello @ffried , makes sense to me!
Created PR to add this functionality: https://github.com/maxim-lobanov/setup-xcode/pull/28

**Comment by maxim-lobanov** [comment]
@ffried , I have released `v1.3.0` with these changes and updated `v1` tag.
Please find more details in https://github.com/maxim-lobanov/setup-xcode/releases/tag/v1.3.0
And let me know if you have any questions
