### ISSUE TITLE
README isn’t clear on definition of latest

### ISSUE THREAD

**Issue by mxcl** [maxim-lobanov/setup-xcode#3]
Is the latest version the GitHub Actions default, or is it (eg. right now) Xcode 12 beta?

**Comment by maxim-lobanov** [comment]
Hello,
`latest` points to the Xcode 12 beta.
I am not sure that it makes sense to have `default` option in task because if you need default Xcode, you don't need the task :) 
But please let me know if you see use-case

**Comment by mxcl** [comment]
Yeah no need for a `default` setting, I just wanted clarification, since `latest` often means “latest *stable* release”.

Having `latest-stable` would be useful, but I understand that is a maintenance burden for you.

**Comment by maxim-lobanov** [comment]
Released: https://github.com/maxim-lobanov/setup-xcode/releases/tag/v1.1
