### ISSUE TITLE
Startup failure with maxim-lobanov/setup-xcode cannot

### ISSUE THREAD

**Issue by bacnv-1260** [maxim-lobanov/setup-xcode#40]
`maxim-lobanov/setup-xcode@v1 is not allowed to be used in **[my repo]**. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace or match the following: geekyeggo/delete-artifact@v1, machine-learning-apps/pr-comment@master, maierj/fastlane-action@v2.0.1, reviewdog/action-rubocop@*, subosito/flutter-action@v1, webfactory/ssh-agent@v0.5.4`

I get error when try set xcode version, please help

**Comment by maxim-lobanov** [comment]
Hello @bacnv-1260 , As it is said in error message, the admin of your organisation / enterprise don't allow to use third-party actions. You should work with admin of your org to add this action to approved list like it is already done for some other actions listed in error message.
Find more details in the article: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-specific-actions-to-run
