### ISSUE TITLE
cant install new xcode version 13.3

### ISSUE THREAD

**Issue by Rotemsim3339** [maxim-lobanov/setup-xcode#44]
Hi,
i'm running on the newest version        
uses: maxim-lobanov/setup-xcode@v1.4.1
new, i need to install xcode 13.3 but im getting this error:

Switching Xcode to version '13.3'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬──────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │               path               │
├─────────┼──────────┼─────────────┼─────────────┼────────┼──────────────────────────────────┤
│    0    │ '13.2.1' │  '13C100'   │    'GM'     │  true  │ '/Applications/Xcode_13.2.1.app' │
│    1    │ '13.2.0' │   '13C90'   │    'GM'     │  true  │  '/Applications/Xcode_13.2.app'  │
│    2    │ '13.1.0' │ '13A10[30](https://github.com/digibank-il/ios-banking/runs/5968538145?check_suite_focus=true#step:7:30)d'  │    'GM'     │  true  │  '/Applications/Xcode_13.1.app'  │
│    3    │ '13.0.0' │  '13A2[33](https://github.com/digibank-il/ios-banking/runs/5968538145?check_suite_focus=true#step:7:33)'   │    'GM'     │  true  │  '/Applications/Xcode_13.0.app'  │
│    4    │ '12.5.1' │  '12E507'   │    'GM'     │  true  │ '/Applications/Xcode_12.5.1.app' │
│    5    │ '12.4.0' │   '12D4e'   │    'GM'     │  true  │  '/Applications/Xcode_12.4.app'  │
│    6    │ '11.7.0' │  '11E801a'  │    'GM'     │  true  │  '/Applications/Xcode_11.7.app'  │
└─────────┴──────────┴─────────────┴─────────────┴────────┴──────────────────────────────────┘
Error: Could not find Xcode version that satisfied version spec: '13.3'

is there a possibility to add support for this version?

**Comment by maxim-lobanov** [comment]
Duplicate: https://github.com/maxim-lobanov/setup-xcode/issues/42

> I think you are using macos-latest or macos-11 image label. Based on official Actions documentation, Xcode 13.3 is not available on this image: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode so this task can't find it.
> I think it is related to the fact that Apple has dropped support for macOS 11 in Xcode 13.3 and it requires macOS 12+. And based on Actions docs, Xcode 13.3 is available on macOS 12 image: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode
But macOS 12 image is still in private preview in GitHub Actions, see related discussion: https://github.com/actions/virtual-environments/issues/3649

**Comment by mikehardy** [comment]
macos12 is available now in public beta, this can be closed
I came here to check for xcode14 beta availability but don't see it on their virtual environments page yet, so no possibility for this action to see it yet either - not this action's fault.
Cheers!

**Comment by maxim-lobanov** [comment]
@mikehardy they have added Xcode 14 beta recently so I think it will be available very soon: https://github.com/actions/virtual-environments/pull/5703
