### ISSUE TITLE
Github pushing for upgrade to Node.js 16 for actions

### ISSUE THREAD

**Issue by pfeerick** [maxim-lobanov/setup-xcode#49]
Just a heads up - starting to get this message now for a GitHub actions job that uses this action.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: maxim-lobanov/setup-xcode

**Comment by maxim-lobanov** [comment]
@yhkaplan , @pfeerick , I have released version `v1.5.0` with Node16 support:
`- uses: maxim-lobanov/setup-xcode@v1.5.0`

Could you please confirm that it works as expected and I will switch `v1` tag to point to `v1.5.0`

**Comment by maxim-lobanov** [comment]
Updated `v1` tag

**Comment by pfeerick** [comment]
Updated the WiP PR which is resolving some of the lovely depreciation messages starting to roll in from Github, and it ran successfully without any issue. 

Latest run https://github.com/EdgeTX/edgetx/actions/runs/3242147056 vs prior run 
https://github.com/EdgeTX/edgetx/actions/runs/3225186038

So now just need to hunt down which actions have just started triggering this 😆 
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
