### ISSUE TITLE
GitHub warning: the `set-output` command is deprecated

### ISSUE THREAD

**Issue by sebj** [maxim-lobanov/setup-xcode#55]
Currently getting two warnings whenever this step is used in a workflow, both as follows:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by maxim-lobanov** [comment]
Hey @sebj , thank you for report. I will take a look shortly.

**Comment by maxim-lobanov** [comment]
Released version `v1.5.1` with fix: https://github.com/maxim-lobanov/setup-xcode/releases/tag/v1.5.1
Also updated `v1` tag to point to `v1.5.1`

**Comment by sebj** [comment]
Thank you @maxim-lobanov! I can confirm the issue is resolved
