### ISSUE TITLE
Latest-stable points to Xcode Beta 14.1

### ISSUE THREAD

**Issue by gusenico** [maxim-lobanov/setup-xcode#58]
Hi! Currently `latest-stable` is pointing to Xcode 14.1 RC:

```
Run maxim-lobanov/setup-xcode@v1.1
Switching Xcode to version 'latest-stable'...
Xcode is set to '14.1.0'
```

This is still marked as beta on macOS readme: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode

Version | Build | Path
-- | -- | --
14.1 (beta) | 14B5033e | /Applications/Xcode_14.1.app
14.0.1 (default) | 14A400 | /Applications/Xcode_14.0.1.app
14.0 | 14A309 | /Applications/Xcode_14.0.app

**Comment by maxim-lobanov** [comment]
Hi @gusenico ,
Xcode 14.1 RC (14B47) was released on 18 Oct 2022 ([Link](https://xcodereleases.com/)).
And looks like GitHub Actions team is deploying the new image with Xcode 14.1 RC right now: https://github.com/actions/runner-images/pull/6439

Usually, they update docs when deployment is finished (it can take 1-2 days to update all VMs).

**Comment by gusenico** [comment]
Thanks for the fast response! It's sad to realize that Github Actions images can sometimes release something faster than Apple officially does, but I guess you don't have any other way to tell beta from non-beta.
