### ISSUE TITLE
Latest-stable points to Xcode Beta

### ISSUE THREAD

**Issue by victorBaro** [maxim-lobanov/setup-xcode#6]
See attached image, latest-stable points to Xcode 12.2.

As of today (September 23rd), latest stable Xcode version is 12.0. Xcode 12.2 is still in beta.

  
![Screen Shot 2020-09-23 at 2 25 07 PM](https://user-images.githubusercontent.com/994334/94071666-32b14480-fda9-11ea-8fea-a4c7703deb62.png)

![Screen Shot 2020-09-23 at 2 29 14 PM](https://user-images.githubusercontent.com/994334/94071675-3644cb80-fda9-11ea-80f9-470fac982249.png)

**Comment by maxim-lobanov** [comment]
Hello @victorBaro , thank you for reporting this issue!
Acknowledged. 

For previous Xcode versions, GH Actions images have the following approach:
1) stable versions of Xcode were installed to `/Applications/Xcode_<VERSION>.app` and symlink to `/Applications/Xcode_<VERSION>_beta.app`
2) beta versions were installed to `/Applications/Xcode_<VERSION>_beta.app` and was symlinked to `/Applications/Xcode_<VERSION.app`
Action determines stable version based on this logic.

Recently, this logic was changed and Xcode 12.2 beta installed in `/Applications/Xcode_12.2.app` and no symlink to `/Applications/Xcode_12.2_beta.app`.

I guess we need more reliable way to check whether Xcode is stable or not.
I think we can parse `<XCODE_ROOT>/Contents/Resources/LicenseInfo.plist` file that contains property `licenseType`:

![image](https://user-images.githubusercontent.com/16715858/94104782-8622a180-fe40-11ea-9557-bbab10772b8b.png)
![image](https://user-images.githubusercontent.com/16715858/94104787-8b7fec00-fe40-11ea-88e8-bd16a006273d.png)

I will try to provide solution soon

**Comment by maxim-lobanov** [comment]
Draft PR: https://github.com/maxim-lobanov/setup-xcode/pull/7

**Comment by maxim-lobanov** [comment]
@victorBaro , I have merged fix to master via #7 
Could you please try to specify `uses: maxim-lobanov/setup-xcode@master` in your workflow and confirm that everything works as expected for you?
After that I will update tags.

**Comment by maxim-lobanov** [comment]
Updated v1.1 tag, `uses: maxim-lobanov/setup-xcode@v1.1` should work as expected.

**Comment by victorBaro** [comment]
Thanks for the quick response @maxim-lobanov 
All good now 👍
