### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by Pesa** [maxim-lobanov/setup-xcode#68]
Node 16 is EOL. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by maxim-lobanov** [comment]
@Pesa thank you for raising this point!
Will update action soon

**Comment by maxim-lobanov** [comment]
Published release v1.6.0 with Node.js 20: https://github.com/maxim-lobanov/setup-xcode/releases/tag/v1.6.0
+ Updated `v1` tag to point to `v1.6.0`
<img width="221" alt="image" src="https://github.com/maxim-lobanov/setup-xcode/assets/16715858/f66cf1f1-2dfc-48b7-a16a-5e0e0f7a4b25">
