### ISSUE TITLE
latest-stable includes release candidates

### ISSUE THREAD

**Issue by mattalbr** [maxim-lobanov/setup-xcode#87]
From a run today:

```
Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version 'latest-stable'...
Xcode is set to 16.1.0 (16B40)
```

Based on https://xcodereleases.com/ 16.1.0 does not have a `Release` build yet, just an `RC`, and 16B40 is 16.1 RC 1.

I think latest-stable should exclude release candidates. Thank you!

**Comment by maxim-lobanov** [comment]
Hello 👋 ,
Unfortunately, it is not easy to do.

This action doesn't have hardcoded list of Xcode versions (to avoid maintenance concerns and slowness with updates).
It scans and finds Xcode versions on GitHub Actions VM and get release type directly from Xcode.

Unfortunately, Apple doesn't really distinguish release candidates and release versions. Release candidates are marked as release (check `cat /Applications/Xcode_16.1.app/Contents/Resources/LicenseInfo.plist`)
Pretty often, they just promote "release candidate" to "release" version without any updates.
For example, on https://xcodereleases.com/, you can see that `Xcode 16.1 Release` and `Xcode 16.1 RC1` both have build `16B40`. So, release candidate just becomes release version at some moment.

**Comment by mattalbr** [comment]
Got it, thank you for the explanation! I think it's fine to close this as Won't Fix Infeasible in that case.
